const products = [
  {
    id: 1,
    name: 'test',
    sku: '123456',
    channel_name: '123456',
    package_details: {
      length: 1,
      width: 1,
      height: 1,
      dead_weight: 1,
    },
    images: ['url1', 'url2'],
    status_name: 'Not Requested',
    status_id: 0,
  },
  {
    id: 2,
    name: 'Product 2',
    sku: '789012',
    channel_name: '789012',
    package_details: {
      length: 2,
      width: 2,
      height: 2,
      dead_weight: 2,
    },
    images: ['url3', 'url4'],
    status_name: 'Request Raised',
    status_id: 2,
  },
  {
    id: 3,
    name: 'Product 3',
    sku: '345678',
    channel_name: '345678',
    package_details: {
      length: 3,
      width: 3,
      height: 3,
      dead_weight: 3,
    },
    images: ['url5', 'url6'],
    status_name: 'Request Accepted',
    status_id: 1,
  },
  {
    id: 4,
    name: 'Product 4',
    sku: '901234',
    channel_name: '901234',
    package_details: {
      length: 4,
      width: 4,
      height: 4,
      dead_weight: 4,
    },
    images: ['url7', 'url8'],
    status_name: 'Request Rejected',
    status_id: 3,
  },
  {
    id: 5,
    name: 'Product 5',
    sku: '567890',
    channel_name: '567890',
    package_details: {
      length: 5,
      width: 5,
      height: 5,
      dead_weight: 5,
    },
    images: ['url9', 'url10'],
    status_name: 'Not Requested',
    status_id: 0,
  },
  {
    id: 6,
    name: 'Product 6',
    sku: '234567',
    channel_name: '234567',
    package_details: {
      length: 6,
      width: 6,
      height: 6,
      dead_weight: 6,
    },
    images: ['url11', 'url12'],
    status_name: 'Unfreezed',
    status_id: 4,
  },
  {
    id: 7,
    name: 'Product 7',
    sku: '777777',
    channel_name: '777777',
    package_details: {
      length: 7,
      width: 7,
      height: 7,
      dead_weight: 7,
    },
    images: ['url13', 'url14'],
    status_name: 'Not Requested',
    status_id: 0,
  },
  {
    id: 8,
    name: 'Product 8',
    sku: '888888',
    channel_name: '888888',
    package_details: {
      length: 8,
      width: 8,
      height: 8,
      dead_weight: 8,
    },
    images: ['url15', 'url16'],
    status_name: 'Action required',
    status_id: 5,
  },
  {
    id: 9,
    name: 'Product 9',
    sku: '999999',
    channel_name: '999999',
    package_details: {
      length: 9,
      width: 9,
      height: 9,
      dead_weight: 9,
    },
    images: ['url17', 'url18'],
    status_name: 'Request Raised',
    status_id: 2,
  },
  {
    id: 10,
    name: 'Product 10',
    sku: '101010',
    channel_name: '101010',
    package_details: {
      length: 10,
      width: 10,
      height: 10,
      dead_weight: 10,
    },
    images: ['url19', 'url20'],
    status_name: 'Unfreezed',
    status_id: 4,
  },
];

export default products;
