const truckTypes = [
    { label: "32 Feet Single Axle", value: "32 Feet Single Axle" },
    { label: "32 Feet Single Axle High Cube", value: "32 Feet Single Axle High Cube" },
    { label: "32 Feet Multi Axle", value: "32 Feet Multi Axle" },
    { label: "32 Feet Multi Axle High Cube", value: "32 Feet Multi Axle High Cube" },
    { label: "32 Feet Triple Axle", value: "32 Feet Triple Axle" },
    { label: "22 Feet", value: "22 Feet" },
    { label: "24 Feet", value: "24 Feet" },
    { label: "20 Feet", value: "20 Feet" },
    { label: "22 Feet Open", value: "22 Feet Open" },
    { label: "10 Whl", value: "10 Whl" },
    { label: "24 Feet Open", value: "24 Feet Open" },
    { label: "20 Feet Open", value: "20 Feet Open" },
    { label: "17 Feet Open", value: "17 Feet Open" },
    { label: "12 Whl", value: "12 Whl" },
    { label: "14 Whl", value: "14 Whl" }
];

const materialTypes = [
    { label: "Agriculture", value: "Agriculture" },
    { label: "Alcoholic Beverage", value: "Alcoholic Beverage" },
    { label: "Auto Parts", value: "Auto Parts" },
    { label: "Bags", value: "Bags" },
    { label: "Beverages", value: "Beverages" },
    { label: "Bundle / Rolls", value: "Bundle / Rolls" },
    { label: "Carton Box", value: "Carton Box" },
    { label: "Carton box / FMCG", value: "Carton box / FMCG" },
    { label: "Drum/barrel", value: "Drum/barrel" },
    { label: "Electronic Goods", value: "Electronic Goods" },
    { label: "Empty Bottle", value: "Empty Bottle" },
    { label: "Empty Cylinder", value: "Empty Cylinder" },
    { label: "Engineering materials", value: "Engineering materials" },
    { label: "FMCG", value: "FMCG" },
    { label: "Footwears", value: "Footwears" },
    { label: "Furniture", value: "Furniture" },
    { label: "Garment bundle", value: "Garment bundle" },
    { label: "Glass", value: "Glass" },
    { label: "Hardware (Door / Windows)", value: "Hardware (Door / Windows)" },
    { label: "Hardware (Pipes / Tiles)", value: "Hardware (Pipes / Tiles)" },
    { label: "Industrial Goods", value: "Industrial Goods" },
    { label: "Kitchenware", value: "Kitchenware" },
    { label: "Medicine", value: "Medicine" },
    { label: "Milk Products", value: "Milk Products" },
    { label: "Others", value: "Others" },
    { label: "Packaging Materials", value: "Packaging Materials" },
    { label: "Paint", value: "Paint" },
    { label: "Pallet / Panel", value: "Pallet / Panel" },
    { label: "Paper Bundle", value: "Paper Bundle" },
    { label: "Parcel", value: "Parcel" },
    { label: "Plywood", value: "Plywood" },
    { label: "Sack (Jute/Plastic)", value: "Sack (Jute/Plastic)" },
    { label: "Scrap", value: "Scrap" },
    { label: "Solid Sheets", value: "Solid Sheets" },
    { label: "Textiles", value: "Textiles" },
    { label: "Tyre", value: "Tyre" },
    { label: "Waste Cloths", value: "Waste Cloths" },
    { label: "Waste Material", value: "Waste Material" }
];

const weights = [
    { label: "5", value: 5 },
    { label: "6", value: 6 },
    { label: "6.5", value: 6.5 },
    { label: "7", value: 7 },
    { label: "7.5", value: 7.5 },
    { label: "8", value: 8 },
    { label: "9", value: 9 },
    { label: "10", value: 10 },
    { label: "11", value: 11 },
    { label: "12", value: 12 },
    { label: "13", value: 13 },
    { label: "14", value: 14 },
    { label: "15", value: 15 },
    { label: "16", value: 16 },
    { label: "17", value: 17 },
    { label: "18", value: 18 },
    { label: "19", value: 19 },
    { label: "20", value: 20 },
    { label: "21", value: 21 },
    { label: "22", value: 22 },
    { label: "23", value: 23 },
    { label: "24", value: 24 },
    { label: "25", value: 25 },
    { label: "26", value: 26 },
    { label: "27", value: 27 },
    { label: "28", value: 28 },
    { label: "29", value: 29 },
    { label: "30", value: 30 },
    { label: "31", value: 31 },
    { label: "32", value: 32 }
];

module.exports = {
    truckTypes: truckTypes,
    materialTypes: materialTypes,
    weights: weights
}