import { All, Delivered, InTransit, New, PickupMenifests, ReadyToShip, Rto } from '../components';

export const ordersTabs = [
  {
    title: 'New',
    id: 'new',
  },
  {
    title: 'Ready To Ship',
    id: 'invoiced',
  },
  {
    title: 'Pickups & Menifests',
    id: 'manifested',
  },
  {
    title: 'In Transit',
    id: 'in transit',
  },
  {
    title: 'Delivered',
    id: 'Delivered',
  },
  {
    title: 'RTO',
    id: 'RTO',
  },
  {
    title: 'All',
    id: 'all',
  },
];

export const trip_status_filter = [
  {
    title: 'All',
    id: 'all',
  },
  {
    title: 'Booking Price Pending',
    id: 'booking_price_pending',
  },
  {
    title: 'Booking Pending',
    id: 'booking_pending',
  },
  {
    title: 'Booking Confirmed',
    id: 'booking_confirmed',
  },
  {
    title: 'Booking Rejected',
    id: 'booking_rejected',
  },
];

export const readyToShipOptions = [
  // { id: '3', type: 'Pickup Exception' },
  // { id: '4', type: 'Pickup Queued' },
  // { id: '5', type: 'Pickup Rescheduled' },
  // { id: '6', type: 'Pickup Scheduled' },
  { id: '7', type: 'Ready to Ship' },
];

export const pickupOptions = [
  { id: '1', type: 'Out For Pickup' },
  { id: '2', type: 'Pickup Error' },
  { id: '12', type: 'Pickup Scheduled' },
  { id: '13', type: 'Pickup Rescheduled' },
  { id: '14', type: 'Partially Completed' },
  { id: '15', type: 'Pickup Exception' },
  { id: '16', type: 'Pickup Completed' },
  { id: '17', type: 'Manifest Cancelled' },
];

export const inTransitOptions = [
  { id: '18', type: 'Damaged' },
  { id: '19', type: 'Delayed' },
  { id: '20', type: 'Destroyed' },
  { id: '21', type: 'In Transit' },
  { id: '22', type: 'Out for Delivery' },
  { id: '23', type: 'Picked Up' },
  { id: '24', type: 'Reached Destination Hub' },
  { id: '25', type: 'Shipped' },
  { id: '26', type: 'Undelivered' },
  { id: '27', type: 'On Hold' },
  { id: '28', type: 'Connection Aligned' },
  { id: '29', type: 'Custom Cleared' },
  { id: '30', type: 'In Flight' },
  { id: '31', type: 'In Transit Overseas' },
  { id: '32', type: 'Reached Overseas Warehouse' },
  { id: '33', type: 'Custom Cleared Overseas' },
];

export const rtoOptions = [
  { id: '34', type: 'RTO Initiated' },
  { id: '35', type: 'RTO Delivered' },
  { id: '36', type: 'RTO Acknowledged' },
  { id: '37', type: 'RTO Rejected' },
  { id: '38', type: 'RTO In Transit' },
  { id: '39', type: 'RTO NDR' },
];

export const allOptions = [
  { id: '1', type: 'Allocation in Progress' },
  { id: '2', type: 'Archived' },
  { id: '3', type: 'Booked' },
  { id: '4', type: 'Box Packing' },
  { id: '5', type: 'Canceled' },
  { id: '6', type: 'Cancellation Requested' },
  { id: '7', type: 'Connection Aligned' },
  { id: '8', type: 'Custom Cleared' },
  { id: '9', type: 'Custom Cleared Overseas' },
  { id: '10', type: 'Damaged' },
  { id: '11', type: 'Darkstore Scheduled' },
  { id: '12', type: 'Delivered' },
  { id: '13', type: 'Delivery Delayed' },
  { id: '14', type: 'Destroyed' },
  { id: '15', type: 'Disposed Off' },
  { id: '16', type: 'ePayment Failed' },
  { id: '17', type: 'FC Allocated' },
  { id: '18', type: 'FC Manifest Generated' },
  { id: '19', type: 'Fulfilled' },
  { id: '20', type: 'Handover Exception' },
  { id: '21', type: 'Handover to Courier' },
  { id: '22', type: 'In Flight' },
  { id: '23', type: 'In Transit' },
  { id: '24', type: 'In Transit Overseas' },
  { id: '25', type: 'Invoiced' },
  { id: '26', type: 'Issue Related to the Recipient' },
  { id: '27', type: 'Lost' },
  { id: '28', type: 'Misrouted' },
  { id: '29', type: 'New' },
  { id: '30', type: 'On Hold' },
  { id: '31', type: 'ON HOLD CUSTOM OVERSEAS' },
  { id: '32', type: 'Out for Delivery' },
  { id: '33', type: 'Out For Pickup' },
  { id: '34', type: 'Out of Stock' },
  { id: '35', type: 'Packed' },
  { id: '36', type: 'Packed Exception' },
  { id: '37', type: 'Picked Up' },
  { id: '38', type: 'Picklist Generated' },
  { id: '39', type: 'Pickup Error' },
  { id: '40', type: 'Pickup Exception' },
  { id: '41', type: 'Pickup Queued' },
  { id: '42', type: 'Pickup Rescheduled' },
  { id: '43', type: 'Pickup Scheduled' },
  { id: '44', type: 'Processed at Warehouse' },
  { id: '45', type: 'PROCESSING IN CUSTOMS OVERSEAS' },
  { id: '46', type: 'QC Failed' },
  { id: '47', type: 'Reached at Destination Hub' },
  { id: '48', type: 'Reached Back at Seller City' },
  { id: '49', type: 'REACHED CUSTOM OVERSEAS' },
  { id: '50', type: 'Reached Overseas Warehouse' },
  { id: '51', type: 'Reached Warehouse' },
  { id: '52', type: 'Ready to Pack' },
  { id: '53', type: 'Ready to Ship' },
  { id: '54', type: 'Return Acknowledged' },
  { id: '55', type: 'Return Cancellation Requested' },
  { id: '56', type: 'Return Cancelled' },
  { id: '57', type: 'Return Delivered' },
  { id: '58', type: 'Return in Transit' },
  { id: '59', type: 'Return Initiated' },
  { id: '60', type: 'Return Out for Delivery' },
  { id: '61', type: 'Return Out for Pickup' },
  { id: '62', type: 'Return Pending' },
  { id: '63', type: 'Return Picked Up' },
  { id: '64', type: 'Return Pickup Cancelled' },
  { id: '65', type: 'Return Pickup Error' },
  { id: '66', type: 'Return Pickup Exception' },
  { id: '67', type: 'Return Pickup Generated' },
  { id: '68', type: 'Return Pickup Queued' },
  { id: '69', type: 'Return Pickup Rescheduled' },
  { id: '70', type: 'Return Undelivered' },
  { id: '71', type: 'Returned' },
  { id: '72', type: 'Rider Assigned' },
  { id: '73', type: 'Rider Reached Drop' },
  { id: '74', type: 'Rider Reached Pickup' },
  { id: '75', type: 'Rider Unassigned' },
  { id: '76', type: 'RTO Acknowledged' },
  { id: '77', type: 'RTO Delivered' },
  { id: '78', type: 'RTO in Transit' },
  { id: '79', type: 'RTO Initiated' },
  { id: '80', type: 'RTO Lock' },
  { id: '81', type: 'RTO NDR' },
  { id: '82', type: 'RTO OFD' },
  { id: '83', type: 'RTO Requested' },
  { id: '84', type: 'Searching for Rider' },
  { id: '85', type: 'Self Fulfilled' },
  { id: '86', type: 'Shipped' },
  { id: '87', type: 'Undelivered' },
  { id: '88', type: 'Unmapped' },
  { id: '89', type: 'Untraceable' },
];
