export * from './dashboard';
export * from './log-in';
export * from './sign-up';
export * from './orders';
export * from './add-order';
export * from './order-track-details';
export * from './return';
export * from './weight-discrepancy'
export * from './kyc';
export * from './weight-freeze';
export * from './settings';
export * from './company-profile'
export * from './change-password'
export * from './manage_pickup_address'
export * from './bank_details'
export * from './home'
export * from './book-truck'
export * from './indent'
export * from './kyc-verfication'
export * from './catalogue'
export * from './courier'
export * from './manage-role'
export * from './early-cod'

